import { analysisReport, filterAnalysisItems, getCategoryDistribution, getDashboardMetrics } from './report-data.mjs';
import { generateQuestionScript } from './report-api.js';
const deviationMeta = Object.freeze({ positive: { label: '正偏离', tone: 'positive' }, negative_wording: { label: '措辞可改', tone: 'wording' }, negative_real: { label: '真实负偏离', tone: 'negative' } });
const element = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
function renderHeader(report) { document.querySelector('#report-title').textContent = `${report.projectName} · AI 分析报告`; document.querySelector('#controller-summary').textContent = report.controller.summary; document.querySelector('#controller-vendor').textContent = report.controller.vendor; document.querySelector('#controller-confidence').textContent = `${Math.round(report.controller.confidence * 100)}%`; document.querySelector('#controller-evidence').replaceChildren(...report.suspiciousItems.map((item) => element('li', '', item))); }
function renderKpis(metrics) { const data = [['有效参数', metrics.total, '结构化提取的关键招标条款', 'blue'], ['正偏离（优于要求）', metrics.positiveCount, '讯飞方案可满足或优于要求', 'green'], ['措辞可改', metrics.wordingCount, '建议改为功能或性能指标', 'amber'], ['负偏离（不满足）', metrics.negativeCount, '需重点澄清或形成应对方案', 'red']]; document.querySelector('#report-kpis').replaceChildren(...data.map(([label, value, note, tone]) => { const card = element('article', `summary-card ${tone}`); card.append(element('strong', '', String(value)), element('span', '', label), element('small', '', note)); return card; })); }
function renderChart(report) { const distribution = getCategoryDistribution(report); const stats = Object.keys(distribution).map((category) => { const entries = report.analysisItems.filter((item) => item.category === category); return { category, positive: entries.filter((item) => item.deviation === 'positive').length, wording: entries.filter((item) => item.deviation === 'negative_wording').length, negative: entries.filter((item) => item.deviation === 'negative_real').length }; }); const maximum = Math.max(...stats.map((item) => item.positive + item.wording + item.negative), 1); document.querySelector('#category-chart').replaceChildren(...stats.map((item) => { const column = element('div', 'bar-column'); const stack = element('div', 'bar-stack'); stack.title = `${item.category}：正偏离 ${item.positive}，措辞可改 ${item.wording}，真实负偏离 ${item.negative}`; [['positive', item.positive], ['wording', item.wording], ['negative', item.negative]].forEach(([tone, value]) => { if (!value) return; const segment = element('i', `bar ${tone}`); segment.style.height = `${Math.max(value / maximum * 96, 13)}px`; stack.append(segment); }); column.append(stack, element('span', '', item.category)); return column; })); }
function riskButton(item) { const button = element('button', 'risk-entry', '查看依据 / 生成质疑话术'); button.type = 'button'; button.addEventListener('click', () => openRiskDetail(item)); return button; }
function createRows(items) { return items.map((item) => { const meta = deviationMeta[item.deviation]; const row = element('tr', `analysis-row ${meta.tone}`); const cells = [element('td', 'seq', String(item.seq).padStart(2, '0')), element('td', '', item.category), element('td', 'requirement', item.bidRequirement), element('td', '', item.xunfeiSpec), element('td'), element('td'), element('td', 'operation')]; cells[4].append(element('span', `deviation ${meta.tone}`, meta.label)); cells[5].append(element('span', 'method', item.matchMethod)); if (item.deviation === 'positive') cells[6].textContent = '—'; else cells[6].append(riskButton(item)); row.append(...cells); return row; }); }
function renderTable(report, filter) { const items = filterAnalysisItems(report, filter); document.querySelector('#report-table-body').replaceChildren(...createRows(items)); document.querySelector('#table-count').textContent = `显示 ${items.length} / ${report.analysisItems.length} 项`; }
function bindFilters(report) { document.querySelectorAll('.report-filter').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.report-filter').forEach((candidate) => candidate.setAttribute('aria-pressed', String(candidate === button))); renderTable(report, button.dataset.filter); })); }
function closeRiskDetail() { document.querySelector('#risk-modal')?.remove(); }
function copyText(text, button) { navigator.clipboard?.writeText(text).then(() => { button.textContent = '已复制'; setTimeout(() => { button.textContent = '复制'; }, 1500); }).catch(() => { button.textContent = '请手动复制'; }); }
function openRiskDetail(item) { closeRiskDetail(); const meta = deviationMeta[item.deviation]; const overlay = element('div', 'risk-modal'); overlay.id = 'risk-modal'; const dialog = element('section', 'risk-dialog'); dialog.setAttribute('role', 'dialog'); dialog.setAttribute('aria-modal', 'true'); const close = element('button', 'modal-close', '×'); close.type = 'button'; close.setAttribute('aria-label', '关闭风险详情'); close.addEventListener('click', closeRiskDetail); const title = element('h2', 'risk-title'); title.append(`第 ${item.seq} 项 · ${item.name} `, element('span', `deviation ${meta.tone}`, meta.label), element('span', `risk-level ${item.riskLevel}`, `${item.riskLevel}风险`)); const grid = element('div', 'risk-grid'); [['招标要求', item.bidRequirement], ['讯飞规格', item.xunfeiSpec], ['偏离分析（依据）', item.riskExplanation], ['应对建议', item.action]].forEach(([label, value]) => { const box = element('div', 'risk-field'); box.append(element('label', '', label), element('p', '', value)); grid.append(box); }); const action = element('div', 'script-area'); const generate = element('button', 'generate-script', '生成质疑话术'); generate.type = 'button'; const output = element('div', 'script-output'); generate.addEventListener('click', async () => { generate.disabled = true; generate.textContent = 'AI 生成中…'; output.replaceChildren(element('p', 'loading-script', 'AI 正在根据条款与偏离依据生成质疑话术…')); try { const result = await generateQuestionScript(item); renderScript(output, result.script, result.source); } catch (_) { renderScript(output, item.questionScript, 'template'); } finally { generate.disabled = false; generate.textContent = '重新生成质疑话术'; } }); action.append(generate, output); dialog.append(close, title, grid, action); overlay.append(dialog); overlay.addEventListener('click', (event) => { if (event.target === overlay) closeRiskDetail(); }); document.body.append(overlay); }
function renderScript(output, script, source) { const card = element('div', 'script-card'); const head = element('div', 'script-head'); head.append(element('strong', '', '质疑话术'), element('span', 'script-src', source === 'llm' ? 'AI 生成' : '模板生成')); const copy = element('button', 'copy-btn', '复制'); copy.type = 'button'; copy.addEventListener('click', () => copyText(script, copy)); head.append(copy); card.append(head, element('pre', 'script-text', script)); output.replaceChildren(card); }
renderHeader(analysisReport); renderKpis(getDashboardMetrics(analysisReport)); renderChart(analysisReport); renderTable(analysisReport, 'all'); bindFilters(analysisReport);
